---
- name: Build and push Docker image to Google Artifact Registry
  hosts: localhost
  gather_facts: false
  vars:
    repo_url: "{{ lookup('env', 'REPO_URL') }}"
    image_tag: "{{ lookup('env', 'IMAGE_TAG') }}"
    local_image_name: "nodeapp"

  tasks:
    - name: Build the Docker image
      docker_image:
        name: "{{ local_image_name }}"
        tag: "{{ image_tag }}"
        source: build
        build:
          path: "../../app/"

    - name: Authenticate Docker with Google Artifact Registry
      shell: |
        gcloud auth configure-docker {{ repo_url.split('/')[0] }} --quiet
      args:
        executable: /bin/bash

    - name: Tag the Docker image in the Artifact Registry
      shell: >
        docker tag {{ local_image_name }}:{{ image_tag }} {{ repo_url }}/{{ local_image_name }}:{{ image_tag }}

    - name: Push Docker image to the Artifact Registry
      shell: >
        docker push {{ repo_url }}/{{ local_image_name }}:{{ image_tag }}

